sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 19980727
  # 阿里云OSS对象存储服务
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tR7vV5XT8WBrskzUrAZ
    access-key-secret: txVh5IuAOLdhzRrr9n9SVQuVN4gelm
    bucket-name: gottenzzp-web-springboot